### ISSUE TITLE
掃描私有雲畫面易用性問題

### ISSUE THREAD

**Issue by chiaoyuc** [isuncloud/Android_client#40]
掃描私有雲時的提示會顯示還有x秒結束，但實際上到結束前出現的結果都一直相同，讓人覺得應該早就要結束，不用再多等20秒，建議把倒數計時拿掉。

![client_android_6](https://cloud.githubusercontent.com/assets/11419383/7224309/0e864d38-e763-11e4-8ced-687701267d51.png)

**Comment by neojason** [comment]
保留倒數計時，以便User了解等待狀況
